/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.urbancontent;

import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class details3 extends javax.swing.JFrame {
int r=0,s=0,a=0;
    /**
     * Creates new form details3
     */
    public details3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jCheckBox24 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        r1 = new javax.swing.JCheckBox();
        r5 = new javax.swing.JCheckBox();
        r9 = new javax.swing.JCheckBox();
        r13 = new javax.swing.JCheckBox();
        r17 = new javax.swing.JCheckBox();
        r21 = new javax.swing.JCheckBox();
        r25 = new javax.swing.JCheckBox();
        r23 = new javax.swing.JCheckBox();
        r19 = new javax.swing.JCheckBox();
        r27 = new javax.swing.JCheckBox();
        r3 = new javax.swing.JCheckBox();
        r7 = new javax.swing.JCheckBox();
        r11 = new javax.swing.JCheckBox();
        r15 = new javax.swing.JCheckBox();
        r24 = new javax.swing.JCheckBox();
        r20 = new javax.swing.JCheckBox();
        r28 = new javax.swing.JCheckBox();
        r4 = new javax.swing.JCheckBox();
        r8 = new javax.swing.JCheckBox();
        r12 = new javax.swing.JCheckBox();
        r16 = new javax.swing.JCheckBox();
        r22 = new javax.swing.JCheckBox();
        r18 = new javax.swing.JCheckBox();
        r26 = new javax.swing.JCheckBox();
        r2 = new javax.swing.JCheckBox();
        r6 = new javax.swing.JCheckBox();
        r10 = new javax.swing.JCheckBox();
        r14 = new javax.swing.JCheckBox();
        r29 = new javax.swing.JCheckBox();
        r30 = new javax.swing.JCheckBox();
        r31 = new javax.swing.JCheckBox();
        r32 = new javax.swing.JCheckBox();
        r33 = new javax.swing.JCheckBox();
        r34 = new javax.swing.JCheckBox();
        r35 = new javax.swing.JCheckBox();
        r36 = new javax.swing.JCheckBox();
        r37 = new javax.swing.JCheckBox();
        r43 = new javax.swing.JCheckBox();
        r44 = new javax.swing.JCheckBox();
        r45 = new javax.swing.JCheckBox();
        r46 = new javax.swing.JCheckBox();
        r47 = new javax.swing.JCheckBox();
        r48 = new javax.swing.JCheckBox();
        r49 = new javax.swing.JCheckBox();
        r38 = new javax.swing.JCheckBox();
        r39 = new javax.swing.JCheckBox();
        r40 = new javax.swing.JCheckBox();
        r42 = new javax.swing.JCheckBox();
        r41 = new javax.swing.JCheckBox();
        r50 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jCheckBox8.setText("jCheckBox8");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setText("ROYAL CLASS");

        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel4.setText("A CLASS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel3.setText("S CLASS");

        jCheckBox24.setText("jCheckBox24");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel5.setText("lucky buttons");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 233, 40));

        r1.setBackground(new java.awt.Color(255, 255, 255));
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 20));

        r5.setBackground(new java.awt.Color(255, 255, 255));
        r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5ActionPerformed(evt);
            }
        });
        getContentPane().add(r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, 20));

        r9.setBackground(new java.awt.Color(255, 255, 255));
        r9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9ActionPerformed(evt);
            }
        });
        getContentPane().add(r9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, 20));

        r13.setBackground(new java.awt.Color(255, 255, 255));
        r13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r13ActionPerformed(evt);
            }
        });
        getContentPane().add(r13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, 20));

        r17.setBackground(new java.awt.Color(255, 255, 255));
        r17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r17ActionPerformed(evt);
            }
        });
        getContentPane().add(r17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, 20));

        r21.setBackground(new java.awt.Color(255, 255, 255));
        r21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r21ActionPerformed(evt);
            }
        });
        getContentPane().add(r21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, 20));

        r25.setBackground(new java.awt.Color(255, 255, 255));
        r25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r25ActionPerformed(evt);
            }
        });
        getContentPane().add(r25, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, 20));

        r23.setBackground(new java.awt.Color(255, 255, 255));
        r23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r23ActionPerformed(evt);
            }
        });
        getContentPane().add(r23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, 20));

        r19.setBackground(new java.awt.Color(255, 255, 255));
        r19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r19ActionPerformed(evt);
            }
        });
        getContentPane().add(r19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, 20));

        r27.setBackground(new java.awt.Color(255, 255, 255));
        r27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r27ActionPerformed(evt);
            }
        });
        getContentPane().add(r27, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, 20));

        r3.setBackground(new java.awt.Color(255, 255, 255));
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        getContentPane().add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, 20));

        r7.setBackground(new java.awt.Color(255, 255, 255));
        r7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7ActionPerformed(evt);
            }
        });
        getContentPane().add(r7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, 20));

        r11.setBackground(new java.awt.Color(255, 255, 255));
        r11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r11ActionPerformed(evt);
            }
        });
        getContentPane().add(r11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, 20));

        r15.setBackground(new java.awt.Color(255, 255, 255));
        r15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r15ActionPerformed(evt);
            }
        });
        getContentPane().add(r15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 20));

        r24.setBackground(new java.awt.Color(255, 255, 255));
        r24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r24ActionPerformed(evt);
            }
        });
        getContentPane().add(r24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, 20));

        r20.setBackground(new java.awt.Color(255, 255, 255));
        r20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r20ActionPerformed(evt);
            }
        });
        getContentPane().add(r20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, 20));

        r28.setBackground(new java.awt.Color(255, 255, 255));
        r28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r28ActionPerformed(evt);
            }
        });
        getContentPane().add(r28, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, 20));

        r4.setBackground(new java.awt.Color(255, 255, 255));
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });
        getContentPane().add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, 20));

        r8.setBackground(new java.awt.Color(255, 255, 255));
        r8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8ActionPerformed(evt);
            }
        });
        getContentPane().add(r8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 20));

        r12.setBackground(new java.awt.Color(255, 255, 255));
        r12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r12ActionPerformed(evt);
            }
        });
        getContentPane().add(r12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, 20));

        r16.setBackground(new java.awt.Color(255, 255, 255));
        r16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r16ActionPerformed(evt);
            }
        });
        getContentPane().add(r16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, 20));

        r22.setBackground(new java.awt.Color(255, 255, 255));
        r22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r22ActionPerformed(evt);
            }
        });
        getContentPane().add(r22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 20));

        r18.setBackground(new java.awt.Color(255, 255, 255));
        r18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r18ActionPerformed(evt);
            }
        });
        getContentPane().add(r18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, 20));

        r26.setBackground(new java.awt.Color(255, 255, 255));
        r26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r26ActionPerformed(evt);
            }
        });
        getContentPane().add(r26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, 20));

        r2.setBackground(new java.awt.Color(255, 255, 255));
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        getContentPane().add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, 20));

        r6.setBackground(new java.awt.Color(255, 255, 255));
        r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6ActionPerformed(evt);
            }
        });
        getContentPane().add(r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, 20));

        r10.setBackground(new java.awt.Color(255, 255, 255));
        r10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r10ActionPerformed(evt);
            }
        });
        getContentPane().add(r10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, 20));

        r14.setBackground(new java.awt.Color(255, 255, 255));
        r14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r14ActionPerformed(evt);
            }
        });
        getContentPane().add(r14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, 20));

        r29.setBackground(new java.awt.Color(255, 255, 255));
        r29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r29ActionPerformed(evt);
            }
        });
        getContentPane().add(r29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, 20));

        r30.setBackground(new java.awt.Color(255, 255, 255));
        r30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r30ActionPerformed(evt);
            }
        });
        getContentPane().add(r30, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, 20));

        r31.setBackground(new java.awt.Color(255, 255, 255));
        r31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r31ActionPerformed(evt);
            }
        });
        getContentPane().add(r31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, 20));

        r32.setBackground(new java.awt.Color(255, 255, 255));
        r32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r32ActionPerformed(evt);
            }
        });
        getContentPane().add(r32, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, 20));

        r33.setBackground(new java.awt.Color(255, 255, 255));
        r33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r33ActionPerformed(evt);
            }
        });
        getContentPane().add(r33, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, 20));

        r34.setBackground(new java.awt.Color(255, 255, 255));
        r34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r34ActionPerformed(evt);
            }
        });
        getContentPane().add(r34, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, 20));

        r35.setBackground(new java.awt.Color(255, 255, 255));
        r35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r35ActionPerformed(evt);
            }
        });
        getContentPane().add(r35, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, 20));

        r36.setBackground(new java.awt.Color(255, 255, 255));
        r36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r36ActionPerformed(evt);
            }
        });
        getContentPane().add(r36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 20));

        r37.setBackground(new java.awt.Color(255, 255, 255));
        r37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r37ActionPerformed(evt);
            }
        });
        getContentPane().add(r37, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, 20));

        r43.setBackground(new java.awt.Color(255, 255, 255));
        r43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r43ActionPerformed(evt);
            }
        });
        getContentPane().add(r43, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, 20));

        r44.setBackground(new java.awt.Color(255, 255, 255));
        r44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r44ActionPerformed(evt);
            }
        });
        getContentPane().add(r44, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, 20));

        r45.setBackground(new java.awt.Color(255, 255, 255));
        r45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r45ActionPerformed(evt);
            }
        });
        getContentPane().add(r45, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, 20));

        r46.setBackground(new java.awt.Color(255, 255, 255));
        r46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r46ActionPerformed(evt);
            }
        });
        getContentPane().add(r46, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, -1, 20));

        r47.setBackground(new java.awt.Color(255, 255, 255));
        r47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r47ActionPerformed(evt);
            }
        });
        getContentPane().add(r47, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, -1, 20));

        r48.setBackground(new java.awt.Color(255, 255, 255));
        r48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r48ActionPerformed(evt);
            }
        });
        getContentPane().add(r48, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, -1, 20));

        r49.setBackground(new java.awt.Color(255, 255, 255));
        r49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r49ActionPerformed(evt);
            }
        });
        getContentPane().add(r49, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, -1, 20));

        r38.setBackground(new java.awt.Color(255, 255, 255));
        r38.setEnabled(false);
        r38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r38ActionPerformed(evt);
            }
        });
        getContentPane().add(r38, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        r39.setBackground(new java.awt.Color(255, 255, 255));
        r39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r39ActionPerformed(evt);
            }
        });
        getContentPane().add(r39, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, 20));

        r40.setBackground(new java.awt.Color(255, 255, 255));
        r40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r40ActionPerformed(evt);
            }
        });
        getContentPane().add(r40, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, 20));

        r42.setBackground(new java.awt.Color(255, 255, 255));
        r42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r42ActionPerformed(evt);
            }
        });
        getContentPane().add(r42, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, 20));

        r41.setBackground(new java.awt.Color(255, 255, 255));
        r41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r41ActionPerformed(evt);
            }
        });
        getContentPane().add(r41, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, 20));

        r50.setBackground(new java.awt.Color(255, 255, 255));
        r50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r50ActionPerformed(evt);
            }
        });
        getContentPane().add(r50, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/uc.JPG"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/back.JPG"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 34, 29));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("(");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText(")");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/white.jpg"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
    if (r3.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r3ActionPerformed

    private void r7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7ActionPerformed
       if (r7.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_r7ActionPerformed

    private void r10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r10ActionPerformed
     if (r10.isSelected());
JOptionPane.showMessageDialog(null,"congratulations!!  use code:- tri10  for discount");
this.setVisible(false);
new home().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_r10ActionPerformed

    private void r23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r23ActionPerformed
    if (r23.isSelected());
JOptionPane.showMessageDialog(null,"congratulations!!  use code:- tri20  for discount");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r23ActionPerformed

    private void r27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r27ActionPerformed
    if (r27.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_r27ActionPerformed

    private void r8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8ActionPerformed
    if (r8.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r8ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
if (r1.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
    if (r2.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
    if (r4.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r4ActionPerformed

    private void r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5ActionPerformed
    if (r5.isSelected());
JOptionPane.showMessageDialog(null,"congratulations!!  use code:- tri15  for discount");
this.setVisible(false);
new home().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_r5ActionPerformed

    private void r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6ActionPerformed
    if (r6.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r6ActionPerformed

    private void r9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9ActionPerformed
    if (r9.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_r9ActionPerformed

    private void r11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r11ActionPerformed
    if (r11.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r11ActionPerformed

    private void r12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r12ActionPerformed
    if (r12.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r12ActionPerformed

    private void r13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r13ActionPerformed
    if (r13.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r13ActionPerformed

    private void r14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r14ActionPerformed
    if (r14.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r14ActionPerformed

    private void r15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r15ActionPerformed
    if (r15.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r15ActionPerformed

    private void r16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r16ActionPerformed
    if (r16.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r16ActionPerformed

    private void r17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r17ActionPerformed
    if (r17.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r17ActionPerformed

    private void r18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r18ActionPerformed
    if (r18.isSelected());
JOptionPane.showMessageDialog(null,"congratulations!!  use code:- tri10  for discount");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r18ActionPerformed

    private void r19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r19ActionPerformed
    if (r19.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r19ActionPerformed

    private void r20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r20ActionPerformed
    if (r20.isSelected());
JOptionPane.showMessageDialog(null,"congratulations!!  use code:- tri5  for discount");
this.setVisible(false);
new home().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_r20ActionPerformed

    private void r21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r21ActionPerformed
    if (r21.isSelected());
  JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_r21ActionPerformed

    private void r22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r22ActionPerformed
    if (r22.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r22ActionPerformed

    private void r24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r24ActionPerformed
    if (r24.isSelected());
   JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r24ActionPerformed

    private void r25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r25ActionPerformed
    if (r25.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r25ActionPerformed

    private void r26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r26ActionPerformed
    if (r26.isSelected());
  JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_r26ActionPerformed

    private void r28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r28ActionPerformed
    if (r28.isSelected());
JOptionPane.showMessageDialog(null,"congratulations!!  use code:- tri20  for discount");
this.setVisible(false);
new home().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_r28ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void r29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r29ActionPerformed
  if (r29.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_r29ActionPerformed

    private void r30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r30ActionPerformed
if (r30.isSelected());
JOptionPane.showMessageDialog(null,"congratulations!!  use code:- tri10  for discount");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r30ActionPerformed

    private void r31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r31ActionPerformed
if (r31.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r31ActionPerformed

    private void r32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r32ActionPerformed
if (r32.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r32ActionPerformed

    private void r33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r33ActionPerformed
if (r33.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r33ActionPerformed

    private void r34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r34ActionPerformed
if (r34.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r34ActionPerformed

    private void r35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r35ActionPerformed
if (r35.isSelected());
JOptionPane.showMessageDialog(null,"congratulations!!  use code:- tri15  for discount");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r35ActionPerformed

    private void r36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r36ActionPerformed
if (r36.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r36ActionPerformed

    private void r37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r37ActionPerformed
if (r37.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r37ActionPerformed

    private void r38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r38ActionPerformed
if (r38.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r38ActionPerformed

    private void r39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r39ActionPerformed
if (r39.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r39ActionPerformed

    private void r40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r40ActionPerformed
if (r40.isSelected());
JOptionPane.showMessageDialog(null,"congratulations!!  use code:- tri10  for discount");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r40ActionPerformed

    private void r41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r41ActionPerformed
if (r41.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r41ActionPerformed

    private void r42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r42ActionPerformed
if (r42.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r42ActionPerformed

    private void r43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r43ActionPerformed
if (r43.isSelected());
JOptionPane.showMessageDialog(null,"congratulations!!  use code:- tri20  for discount");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r43ActionPerformed

    private void r44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r44ActionPerformed
if (r44.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r44ActionPerformed

    private void r45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r45ActionPerformed
if (r45.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r45ActionPerformed

    private void r46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r46ActionPerformed
if (r46.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r46ActionPerformed

    private void r47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r47ActionPerformed
if (r47.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r47ActionPerformed

    private void r48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r48ActionPerformed
if (r48.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r48ActionPerformed

    private void r49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r49ActionPerformed
if (r49.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r49ActionPerformed

    private void r50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r50ActionPerformed
if (r50.isSelected());
JOptionPane.showMessageDialog(null,"better luck next time");
this.setVisible(false);
new home().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_r50ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        home ab= new home();
        ab.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(details3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(details3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(details3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(details3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new details3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JCheckBox r1;
    private javax.swing.JCheckBox r10;
    private javax.swing.JCheckBox r11;
    private javax.swing.JCheckBox r12;
    private javax.swing.JCheckBox r13;
    private javax.swing.JCheckBox r14;
    private javax.swing.JCheckBox r15;
    private javax.swing.JCheckBox r16;
    private javax.swing.JCheckBox r17;
    private javax.swing.JCheckBox r18;
    private javax.swing.JCheckBox r19;
    private javax.swing.JCheckBox r2;
    private javax.swing.JCheckBox r20;
    private javax.swing.JCheckBox r21;
    private javax.swing.JCheckBox r22;
    private javax.swing.JCheckBox r23;
    private javax.swing.JCheckBox r24;
    private javax.swing.JCheckBox r25;
    private javax.swing.JCheckBox r26;
    private javax.swing.JCheckBox r27;
    private javax.swing.JCheckBox r28;
    private javax.swing.JCheckBox r29;
    private javax.swing.JCheckBox r3;
    private javax.swing.JCheckBox r30;
    private javax.swing.JCheckBox r31;
    private javax.swing.JCheckBox r32;
    private javax.swing.JCheckBox r33;
    private javax.swing.JCheckBox r34;
    private javax.swing.JCheckBox r35;
    private javax.swing.JCheckBox r36;
    private javax.swing.JCheckBox r37;
    private javax.swing.JCheckBox r38;
    private javax.swing.JCheckBox r39;
    private javax.swing.JCheckBox r4;
    private javax.swing.JCheckBox r40;
    private javax.swing.JCheckBox r41;
    private javax.swing.JCheckBox r42;
    private javax.swing.JCheckBox r43;
    private javax.swing.JCheckBox r44;
    private javax.swing.JCheckBox r45;
    private javax.swing.JCheckBox r46;
    private javax.swing.JCheckBox r47;
    private javax.swing.JCheckBox r48;
    private javax.swing.JCheckBox r49;
    private javax.swing.JCheckBox r5;
    private javax.swing.JCheckBox r50;
    private javax.swing.JCheckBox r6;
    private javax.swing.JCheckBox r7;
    private javax.swing.JCheckBox r8;
    private javax.swing.JCheckBox r9;
    // End of variables declaration//GEN-END:variables
}
