/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.urbancontent;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author SAM
 */
public class facial extends javax.swing.JFrame {int a,b;double discount;double amt;

    /**
     * Creates new form facial
     */
    public facial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        tt2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb1 = new javax.swing.JCheckBox();
        ccb2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        city = new javax.swing.JTextField();
        street = new javax.swing.JTextField();
        flat = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        city1 = new javax.swing.JTextField();
        street1 = new javax.swing.JTextField();
        flat1 = new javax.swing.JTextField();
        date1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        time1 = new javax.swing.JTextField();
        ott = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/uc.JPG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/add.JPG"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 38));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/location.JPG"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 26));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/city.JPG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 21));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/time.JPG"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 210, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/str.JPG"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 62, 16));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/flat.JPG"))); // NOI18N
        jLabel5.setText("HOUSE NO .");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 84, 15));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/time2.JPG"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/sum.JPG"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 110, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/it.JPG"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/promo.JPG"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/discount.JPG"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/st.JPG"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        t1.setEnabled(false);
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 70, -1));
        getContentPane().add(tt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 70, -1));

        t3.setEnabled(false);
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 70, -1));

        t4.setEnabled(false);
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 80, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/back.JPG"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 34, 29));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/hair1.JPG"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/facial1.JPG"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/hair2.JPG"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/facial2.JPG"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        cb1.setBackground(new java.awt.Color(255, 255, 255));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        ccb2.setBackground(new java.awt.Color(255, 255, 255));
        ccb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccb2ActionPerformed(evt);
            }
        });
        getContentPane().add(ccb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/continue.JPG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 110, 30));

        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 67, -1));
        getContentPane().add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 62, -1));
        getContentPane().add(flat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 62, -1));

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 100, -1));

        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 410, 100, -1));

        city1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                city1ActionPerformed(evt);
            }
        });
        getContentPane().add(city1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 67, -1));
        getContentPane().add(street1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 62, -1));
        getContentPane().add(flat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 62, -1));

        date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date1ActionPerformed(evt);
            }
        });
        getContentPane().add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 100, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/place.JPG"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 427, 210, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/white.jpg"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));

        time1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time1ActionPerformed(evt);
            }
        });
        getContentPane().add(time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 410, 100, -1));

        ott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ottActionPerformed(evt);
            }
        });
        getContentPane().add(ott, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    saloon ab= new saloon();
            ab.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
       if(cb1.isSelected())
      {
      a=599;
      t1.setText(""+(a+b));
      }
        else
        {
        a=0;
         t1.setText(""+(a+b));
        }
    }//GEN-LAST:event_cb1ActionPerformed

    private void ccb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccb2ActionPerformed
      if(ccb2.isSelected())
        {
        b=999;
           t1.setText(""+(a+b));
        }
        else
        {
        b=0;
        t1.setText(""+(a+b));
        }
    }//GEN-LAST:event_ccb2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        double c,f;
        c=Integer.parseInt(t1.getText());
        String d=tt2.getText();

        switch (d) {
            case "tri10":
            discount=10;
            t3.setText("10%");
            break;
            case "tri15":
            discount=15;
            t3.setText("15%");
            break;
            case "tri20":
            discount=20;
            t3.setText("20%");
            break;
            default:
            t3.setText("0");
          
            break;
        }
        f=c*(discount/100);
        double sb=c-f;
        t4.setText(""+sb);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void city1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_city1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_city1ActionPerformed

    private void date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date1ActionPerformed

    private void time1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        getlastid();
        String sr="Facial";
        String ct=city.getText();
        String dt=date.getText();
        String ti=time.getText();
        String ft=flat.getText();
        String st=street.getText();
        String or=ott.getText();

        amt=Double.parseDouble(t4.getText());
        if (ct.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"City not Entered");
        }
        else if (dt.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Date not Entered");
        }
        else if (ti.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Time not Entered");
        }

        else if (ft.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Flat not Entered");
        }
        else if (st.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Street not Entered");
        }

        //buttongroud
        else
        {
            try
            {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/sample","root", "root");
                Statement stmt = (Statement) con.createStatement();
                String query="INSERT INTO orders values('"+or+"','"+ct+"','"+st+"','"+ft+"','"+ti+"','"+dt+"',"+amt+",'"+sr+"');";
                stmt.executeUpdate(query);
            }
            catch(ClassNotFoundException | SQLException e)

            {
                JOptionPane.showMessageDialog (this, e.getMessage());
            }
        }
        {home ab= new home();
            ab.setVisible(true);
            this.setVisible(false);}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void ottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ottActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ottActionPerformed
 public void getlastid(){
        try
        {   
Class.forName("java.sql.DriverManager");
Connection con = (Connection)
DriverManager.getConnection ("jdbc:mysql://localhost:3306/sample","root", "root");
            String sql = "select max(order_id) from orders";
            Statement stmt = (Statement) con.createStatement();  
             PreparedStatement pst = con.prepareStatement(sql);
            ResultSet  rs = pst.executeQuery();
            rs = stmt.executeQuery(sql);
            if(rs.next())
            {
               int lastid = rs.getInt(1);
                lastid++;
                ott.setText(Integer.toString(lastid));
            }
            
        }
        
      catch(Exception ex){
    JOptionPane.showMessageDialog(this, ex);
            
        }
    
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new facial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox ccb2;
    private javax.swing.JTextField city;
    private javax.swing.JTextField city1;
    private javax.swing.JTextField date;
    private javax.swing.JTextField date1;
    private javax.swing.JTextField flat;
    private javax.swing.JTextField flat1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField ott;
    private javax.swing.JTextField street;
    private javax.swing.JTextField street1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField time;
    private javax.swing.JTextField time1;
    private javax.swing.JTextField tt2;
    // End of variables declaration//GEN-END:variables
}
