/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.urbancontent;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author SAM
 */
public class furniture extends javax.swing.JFrame {double aa,bb,cc,ee,dd,discount,amt;
    /**
     * Creates new form furniture
     */
    public furniture() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        ccb4 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        tt2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        street = new javax.swing.JTextField();
        flat = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        ott = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/uc.JPG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/back.JPG"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 34, 29));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/fur1.JPG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 70, -1, 33));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/assembly.JPG"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/assembly1.JPG"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/door.JPG"))); // NOI18N
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/doora1.JPG"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/doorc1.JPG"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/doora2.JPG"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/doorc2.JPG"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/nf.JPG"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/nf1.JPG"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 250, 80));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/nf2.JPG"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, -1, -1));

        cb1.setBackground(new java.awt.Color(255, 255, 255));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 20, 30));

        cb2.setBackground(new java.awt.Color(255, 255, 255));
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        getContentPane().add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 20, 30));

        cb3.setBackground(new java.awt.Color(255, 255, 255));
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });
        getContentPane().add(cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, 30));

        ccb4.setBackground(new java.awt.Color(255, 255, 255));
        ccb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccb4ActionPerformed(evt);
            }
        });
        getContentPane().add(ccb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, -1, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/add.JPG"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 38));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/location.JPG"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 26));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/city.JPG"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, 21));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/str.JPG"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 62, 16));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/flat.JPG"))); // NOI18N
        jLabel19.setText("HOUSE NO .");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 84, 15));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/time.JPG"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 210, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/time2.JPG"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/sum.JPG"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 110, 30));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/it.JPG"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, 20));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/promo.JPG"))); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, 20));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/discount.JPG"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/st.JPG"))); // NOI18N
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/continue.JPG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 110, 30));

        t1.setEnabled(false);
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 70, -1));
        getContentPane().add(tt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 70, -1));

        t3.setEnabled(false);
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 70, -1));

        t4.setEnabled(false);
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 80, -1));

        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 67, -1));
        getContentPane().add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 62, -1));
        getContentPane().add(flat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 62, -1));

        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 100, -1));

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 100, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/place.JPG"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 210, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/urbancontent/white.jpg"))); // NOI18N
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 580));

        ott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ottActionPerformed(evt);
            }
        });
        getContentPane().add(ott, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        carpenter ab= new carpenter();
        ab.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
double c,f;
        c=Double.parseDouble(t1.getText());
        String d=tt2.getText();

        switch (d) {
        case "tri10":
            discount=10;
            t3.setText("10%");
            break;
        case "tri15":
            discount=15;
            t3.setText("15%");
            break;
        case "tri20":
            discount=20;
            t3.setText("20%");
            break;
        default:
            t3.setText("0");
          
            break;
    }
        f=c*(discount/100);
        double sb=c-f;
        t4.setText(""+sb);      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
         if(cb3.isSelected())
      {
      aa=149;
      t1.setText(""+(aa+bb+cc));
      }
        else
        {
        aa=0;
         t1.setText(""+(aa+bb+cc));
        }
    }//GEN-LAST:event_cb3ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
     if(cb1.isSelected())
      {
      bb=99;
      t1.setText(""+(aa+bb+cc));
      }
        else
        {
        bb=0;
         t1.setText(""+(aa+bb+cc));
        }
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
    if(cb2.isSelected())
      {
      cc=250;
      t1.setText(""+(aa+bb+cc));
      }
        else
        {
        cc=0;
         t1.setText(""+(aa+bb+cc));
        }
    }//GEN-LAST:event_cb2ActionPerformed

    private void ccb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccb4ActionPerformed
       if(ccb4.isSelected())
      {
      cc=149;
      t1.setText(""+(aa+bb+cc));
      }
        else
        {
        cc=0;
         t1.setText(""+(aa+bb+cc));
        }
    }//GEN-LAST:event_ccb4ActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        getlastid();
        String sr="Furniture";
        String ct=city.getText();
        String dt=date.getText();
        String ti=time.getText();
        String ft=flat.getText();
        String st=street.getText();
        String or=ott.getText();

        amt=Double.parseDouble(t4.getText());
        if (ct.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"City not Entered");
        }
        else if (dt.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Date not Entered");
        }
        else if (ti.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Time not Entered");
        }

        else if (ft.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Flat not Entered");
        }
        else if (st.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Street not Entered");
        }

        //buttongroud
        else
        {
            try
            {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)
                DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/sample","root", "root");
                Statement stmt = (Statement) con.createStatement();
                String query="INSERT INTO orders values('"+or+"','"+ct+"','"+st+"','"+ft+"','"+ti+"','"+dt+"',"+amt+",'"+sr+"');";
                stmt.executeUpdate(query);
            }
            catch(ClassNotFoundException | SQLException e)

            {
                JOptionPane.showMessageDialog (this, e.getMessage());
            }
        }
        {home ab= new home();
            ab.setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ottActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ottActionPerformed

     public void getlastid(){
        try
        {   
Class.forName("java.sql.DriverManager");
Connection con = (Connection)
DriverManager.getConnection ("jdbc:mysql://localhost:3306/sample","root", "root");
            String sql = "select max(order_id) from orders";
            Statement stmt = (Statement) con.createStatement();  
             PreparedStatement pst = con.prepareStatement(sql);
            ResultSet  rs = pst.executeQuery();
            rs = stmt.executeQuery(sql);
            if(rs.next())
            {
               int lastid = rs.getInt(1);
                lastid++;
                ott.setText(Integer.toString(lastid));
            }
            
        }
        
      catch(Exception ex){
    JOptionPane.showMessageDialog(this, ex);
            
        }
    
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(furniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(furniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(furniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(furniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new furniture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox ccb4;
    private javax.swing.JTextField city;
    private javax.swing.JTextField date;
    private javax.swing.JTextField flat;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField ott;
    private javax.swing.JTextField street;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField time;
    private javax.swing.JTextField tt2;
    // End of variables declaration//GEN-END:variables
}
